# Règles de redirection
[[redirects]]
  from = "/ancienne-page"
  to = "/nouvelle-page"
  status = 301
  force = true

[[redirects]]
  from = "/page-non-trouvee"
  to = "/404.html"
  status = 404

# Règles de gestion des en-têtes HTTP
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Configuration des fonctions Netlify
[functions]
  name = "exemple-fonction"
  path = "fonctions/exemple.js"
  memory = 256

# Configuration des fonctions Edge
[[plugins]]
  package = "@netlify/plugin-functions"
  [plugins.inputs]
    node_bundler = "esbuild"

# Configuration générale
[build]
  command = "npm run build"
  publish = "dossier-de-sortie"

[context.production]
  command = "npm run build:production"
